export interface ConnectionData {
    parameters?: {
        "port": string,
        "read-only": string,
        "swap-red-blue": string,
        "cursor": string,
        "color-depth": string,
        "force-lossless": string,
        "clipboard-encoding": string,
        "disable-copy": string,
        "disable-paste": string,
        "dest-port": string,
        "recording-exclude-output": string,
        "recording-exclude-mouse": string,
        "recording-include-keys": string,
        "create-recording-path": string,
        "enable-sftp": string,
        "sftp-port": string,
        "sftp-server-alive-interval": string,
        "sftp-disable-download": string,
        "sftp-disable-upload": string,
        "enable-audio": string,
        "wol-send-packet": string,
        "wol-udp-port": string,
        "wol-wait-time": string,
        "username": string,
        "password": string,
        "color-scheme": string,
        "font-size": string,
        "scrollback": string,
        "timezone": string,
        "server-alive-interval": string,
        "backspace": string,
        "terminal-type": string,
        "create-typescript-path": string,
        "hostname": string,
        "host-key": string,
        "private-key": string,
        "passphrase": string,
        domain: string,
        security: { name: string, code: string },
        "disable-auth": string,
        "ignore-cert": string,
        "gateway-domain": string,
        "gateway-hostname": string,
        "gateway-password": string,
        "gateway-port": string,
        "gateway-username": string
    },
    attributes: {
        "failover-only": string,
        "guacd-encryption": {name: string, code: string},
        "weight": string,
        "max-connections": string,
        "guacd-hostname": string,
        "guacd-port": string,
        "max-connections-per-user": string
    },
    name?: string,
    protocol?: {name: string, code: string},
    parentIdentifier?: string,
    identifier?: string
}

export interface NewConnectionModalProps {
    setNewConnectionModal: (value: boolean) => void,
    newConnectionModal: boolean,
    data: ConnectionData[]
}